name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install gfortran and other build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran
          # Add other build dependencies if needed

      - name: Install Python dependencies
        run: |
          pip install -r https://raw.githubusercontent.com/PedroBritodSa/Forecasting_Supermarket_Sales/main/requirements.txt
